In [1]:
#Numpy
#Python Numpy Arrays
import numpy as np

In [4]:
lst = [1,2,3]
arr = np.array(lst) #Single dimensional Array

In [5]:
type(arr)

numpy.ndarray

In [9]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,3,5]
lst3=[1,2,5,3,7]
arr1 = np.array([lst1,lst2,lst3])

In [11]:
arr1.shape

(3, 5)

In [13]:
#Indexing
arr1[1][0]

2

In [14]:
arr1[1][0] = 3

In [15]:
arr1

array([[1, 2, 3, 4, 5],
       [3, 3, 4, 3, 5],
       [1, 2, 5, 3, 7]])

In [24]:
arr1[1]

array([3, 3, 4, 3, 5])

In [25]:
arr2 = np.array([1,3,3])

In [28]:
arr1[2,:]

array([1, 2, 5, 3, 7])

In [29]:
arr1[:,1]

array([2, 3, 2])

In [30]:
arr1[1:,1:3]

array([[3, 4],
       [2, 5]])

In [35]:
arr1[1:,3:]

array([[3, 5],
       [3, 7]])

In [36]:
arr1[:,3:]

array([[4, 5],
       [3, 5],
       [3, 7]])

In [37]:
arr[arr<2]

array([1])

In [38]:
arr1

array([[1, 2, 3, 4, 5],
       [3, 3, 4, 3, 5],
       [1, 2, 5, 3, 7]])

In [39]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 3],
       [3, 4, 3],
       [5, 1, 2],
       [5, 3, 7]])

In [40]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(1,10,3)

array([1, 4, 7])

In [42]:
arr*arr

array([1, 4, 9])

In [45]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [47]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [49]:
np.random.randint(10,50,4).reshape(2,2)

array([[25, 41],
       [25, 45]])

In [51]:
np.random.randn(2,2)

array([[-0.24072344,  0.56008447],
       [ 1.23259634,  0.19568309]])